# CI workflow

name: Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Jobs
jobs:
  # This workflow contains a single job called "test"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '11.0.6'

      # Runs check task
      - name: Test with Gradle
        env:
          DISPLAY: ":1"
        run: ./gradlew --info --stacktrace clean check
